### ISSUE TITLE
fatal pynb error while running fab sync_branch

### ISSUE THREAD

**Issue by tbagnoli** [minodes/pynb#10]
```
(da) Tullios-MBP:da-notebooks tullio.bagnoli$ fab sync_branch:DATA-579-analysis-of-returning-pedestria
[localhost] local: git checkout DATA-579-analysis-of-returning-pedestria
M	requirements.txt
Already on 'DATA-579-analysis-of-returning-pedestria'
Your branch is up to date with 'origin/DATA-579-analysis-of-returning-pedestria'.
Target directory found: ./projects/wifi_analytics/DATA-579-analysis-of-returning-pedestria
Converting Jupyter -> Python notebooks for DATA-579-analysis-of-returning-pedestria (recursively)
[localhost] local: pynb --import-ipynb "./projects/wifi_analytics/DATA-579-analysis-of-returning-pedestria/DATA-579-analysis-of-returning-pedestria.ipynb" --export-pynb "./projects/wifi_analytics/DATA-579-analysis-of-returning-pedestria/DATA-579-analysis-of-returning-pedestria.ipynb.py" --disable-footer --no-exec
Traceback (most recent call last):
  File "/Users/tullio.bagnoli/.pyenv/versions/3.4.3/envs/da/lib/python3.4/site-packages/pkg_resources/__init__.py", line 612, in _build_master
    ws.require(__requires__)
  File "/Users/tullio.bagnoli/.pyenv/versions/3.4.3/envs/da/lib/python3.4/site-packages/pkg_resources/__init__.py", line 918, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/tullio.bagnoli/.pyenv/versions/3.4.3/envs/da/lib/python3.4/site-packages/pkg_resources/__init__.py", line 810, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (setuptools 12.0.5 (/Users/tullio.bagnoli/.pyenv/versions/3.4.3/envs/da/lib/python3.4/site-packages), Requirement.parse('setuptools>=18.5'), {'ipython'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tullio.bagnoli/.pyenv/versions/da/bin/pynb", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/Users/tullio.bagnoli/.pyenv/versions/3.4.3/envs/da/lib/python3.4/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/Users/tullio.bagnoli/.pyenv/versions/3.4.3/envs/da/lib/python3.4/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/tullio.bagnoli/.pyenv/versions/3.4.3/envs/da/lib/python3.4/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/tullio.bagnoli/.pyenv/versions/3.4.3/envs/da/lib/python3.4/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: setuptools>=18.5

Fatal error: local() encountered an error (return code 1) while executing 'pynb --import-ipynb "./projects/wifi_analytics/DATA-579-analysis-of-returning-pedestria/DATA-579-analysis-of-returning-pedestria.ipynb" --export-pynb "./projects/wifi_analytics/DATA-579-analysis-of-returning-pedestria/DATA-579-analysis-of-returning-pedestria.ipynb.py" --disable-footer --no-exec'

Aborting.
```

**Comment by elehcimd** [comment]
I'm not sure why this happened. I suspect it was due to the specific combination of package in your system .  Updating them, we fixed the problem (writing this myself since Tullio works in my team). Therefore closing the issue.
