### ISSUE TITLE
RuntimeError when reproducing example from readme

### ISSUE THREAD

**Issue by robOcity** [minodes/pynb#6]
Running anconda python 3.6 on OS X I get the following error when trying to reproduce the example from the readme.  Love where you are heading with this project!

pynb notebooks/test.py --param a=2 --param b=5
INFO:root:Loading cells from notebooks/test.py
INFO:root:Parameters: {'a': '2', 'b': '5'}
INFO:root:Disable cache: False
INFO:root:Ignore cache: False
INFO:traitlets:Executing notebook with kernel: python3
Traceback (most recent call last):
  File "/Users/rob/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/rob/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/rob/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/Users/rob/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/Users/rob/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/rob/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 444, in initialize
    zmq_ioloop.install()
  File "/Users/rob/anaconda3/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 210, in install
    assert (not ioloop.IOLoop.initialized()) or \
AttributeError: type object 'IOLoop' has no attribute 'initialized'
Traceback (most recent call last):
  File "/Users/rob/anaconda3/bin/pynb", line 11, in <module>
    sys.exit(main())
  File "/Users/rob/anaconda3/lib/python3.6/site-packages/pynb/notebook.py", line 596, in main
    nb.run()
  File "/Users/rob/anaconda3/lib/python3.6/site-packages/pynb/notebook.py", line 577, in run
    ignore_cache=self.args.ignore_cache)
  File "/Users/rob/anaconda3/lib/python3.6/site-packages/pynb/notebook.py", line 358, in process
    ep.preprocess(self.nb, {'metadata': {'path': '.'}})
  File "/Users/rob/anaconda3/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 257, in preprocess
    cwd=path)
  File "/Users/rob/anaconda3/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 241, in start_new_kernel
    kc.wait_for_ready(timeout=startup_timeout)
  File "/Users/rob/anaconda3/lib/python3.6/site-packages/jupyter_client/blocking/client.py", line 120, in wait_for_ready
    raise RuntimeError('Kernel died before replying to kernel_info')
RuntimeError: Kernel died before replying to kernel_info

**Comment by robOcity** [comment]
This was configuration problem on my machine.  Sorry for the false alarm.  

Thanks for making notebooks maintainable in version control!

Best, Rob
